<a href="https://colab.research.google.com/github/tranhuudan-02573/BackupWorkspace/blob/master/Lab_6_20130218_TranHuudan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Na√Øve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**

# Import libraries

In [3]:
# code
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectFromModel
from sklearn import svm
from sklearn import datasets
from sklearn.linear_model import LogisticRegression 
from sklearn import tree
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from prettytable import PrettyTable

from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import CategoricalNB

from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.decomposition import PCA

In [4]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML/lab6'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/ML/lab6

In [5]:
from sklearn import datasets
df = datasets.load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.

In [6]:
# code


X_train, X_test, y_train, y_test = train_test_split(df['data'], df['target'], test_size=0.3, random_state=1)
#Create a Random Forest Classifier
clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_predForest = clf.predict(X_test)

# GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)
y_predNaiveBayes = model.predict(X_test)


t = PrettyTable(["Kernel","accuracy","precision","recall","f1"])


t.add_row(["Forest",accuracy_score(y_test,y_predForest),
           precision_score(y_test,y_predForest,average='macro'),
           recall_score(y_test,y_predForest,average='macro'),
           f1_score(y_test,y_predForest,average='macro')])
t.add_row(["Naive Bayes",accuracy_score(y_test,y_predNaiveBayes),
           precision_score(y_test,y_predNaiveBayes,average='macro'),
           recall_score(y_test,y_predNaiveBayes,average='macro'),
           f1_score(y_test,y_predNaiveBayes,average='macro')])
t

#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')

#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [7]:
#code
data = pd.read_csv('bank.csv')
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [8]:
scaler = StandardScaler()

data2 = [data['age'],data['balance'],data['day'],data['campaign'],data['pdays'],data['previous']]


df_stand = pd.DataFrame(scaler.fit_transform(data2))
df_stand

,0,1,2,3,4,5,6,7,8,9,...,11152,11153,11154,11155,11156,11157,11158,11159,11160,11161
0,-0.393896,1.630755,-0.379352,-0.400295,0.199207,2.217915,-0.303468,-0.209849,2.205783,-0.436227,...,-0.278062,1.603462,-0.236063,-0.284428,1.188749,1.853480,-0.344853,1.343605,0.075854,2.154340
1,2.235404,1.162799,2.234984,2.235553,2.141478,-0.521862,2.231256,2.223057,-0.470898,2.236038,...,2.228012,1.153367,2.225609,0.468470,-2.084171,-0.617827,2.233183,1.125723,-0.623089,-0.575383
2,-0.456060,-0.538858,-0.455931,-0.454732,-0.532879,-0.195698,-0.467210,-0.480729,-0.099136,-0.447841,...,-0.411813,-0.309440,-0.466028,-0.518664,0.355081,0.849512,-0.430292,0.399450,-0.493053,0.147191
3,-0.460665,-0.709024,-0.464440,-0.459087,-0.577701,-0.391397,-0.483584,-0.505810,-0.470898,-0.449425,...,-0.496287,-0.759534,-0.502613,-0.836554,0.293328,-0.617827,-0.474869,-0.835214,-0.590580,-0.495097
4,-0.462967,-0.794107,-0.468694,-0.461264,-0.622523,-0.587095,-0.490134,-0.515843,-0.619602,-0.451537,...,-0.524445,-0.872058,-0.513066,2.007730,0.108068,-0.772283,-0.493442,-1.053096,2.172684,-0.655669
5,-0.461816,-0.751565,-0.466567,-0.460175,-0.607582,-0.521862,-0.486859,-0.510827,-0.545250,-0.451009,...,-0.517406,-0.815796,-0.507840,-0.836554,0.138945,-0.695055,-0.489728,-0.980469,-0.541816,-0.575383

#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [9]:
#code
# encoder = OneHotEncoder(handle_unknown='ignore')
# encoded_cols = pd.DataFrame(encoder.fit_transform(data[['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']]).toarray())

# # ƒê·∫∑t l·∫°i t√™n c√°c c·ªôt ƒë∆∞·ª£c m√£ h√≥a OneHot
# encoded_cols.columns = encoder.get_feature_names(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome'])

# create an instance of OneHotEncoder
encoder = OneHotEncoder(sparse=False)

cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

data3=[data['job'],data['marital'],data['education'],data['default'],data['housing'],data['loan'],data['contact'],data['month'],data['poutcome']]
# data[cat_cols]
# fit and transform the categorical columns
df_encoded = pd.DataFrame(encoder.fit_transform(data[cat_cols]),columns=encoder.get_feature_names_out(cat_cols))

# df_encoded = pd.DataFrame(encoder.fit_transform(data3))

# assign column names to the encoded dataframe
# data3.columns = encoder.get_feature_names(cat_cols)
# df_encoded = pd.DataFrame(encoder.fit_transform(data[cat_cols]))

df_processed = pd.concat([data, df_encoded], axis=1)

# remove the original categorical columns
df_processed.drop(columns=cat_cols, inplace=True)

print(df_processed.columns)

# df_processed

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'deposit', 'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown'],
      dtype='object')

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

#3.3. Apply **Decision tree, Random forest, kNN, Na√ØveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [10]:
#code


X_train, X_test, y_train, y_test = train_test_split(df_processed.drop('deposit', axis=1), df_processed['deposit'], test_size=0.3, random_state=1)

decision = tree.DecisionTreeClassifier()
decision.fit(X_train, y_train) 
y_predDes = decision.predict(X_test)


clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_predForest = clf.predict(X_test)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_predKnn = neigh.predict(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_predNaiveBayes = model.predict(X_test)


t = PrettyTable(["Regression","accuracy","precision","recall","f1"])

t.add_row(["DecisionTree",accuracy_score(y_test,y_predDes),
           precision_score(y_test,y_predDes,average='macro'),
           recall_score(y_test,y_predDes,average='macro'),
           f1_score(y_test,y_predDes,average='macro')])


t.add_row(["kNN",accuracy_score(y_test,y_predKnn),
           precision_score(y_test,y_predKnn,average='macro'),
           recall_score(y_test,y_predKnn,average='macro'),
           f1_score(y_test,y_predKnn,average='macro')])

t.add_row(["Forest",accuracy_score(y_test,y_predForest),
           precision_score(y_test,y_predForest,average='macro'),
           recall_score(y_test,y_predForest,average='macro'),
           f1_score(y_test,y_predForest,average='macro')])
t.add_row(["Naive Bayes",accuracy_score(y_test,y_predNaiveBayes),
           precision_score(y_test,y_predNaiveBayes,average='macro'),
           recall_score(y_test,y_predNaiveBayes,average='macro'),
           f1_score(y_test,y_predNaiveBayes,average='macro')])


print(t)

+--------------+--------------------+--------------------+--------------------+--------------------+
|  Regression  |      accuracy      |     precision      |       recall       |         f1         |
+--------------+--------------------+--------------------+--------------------+--------------------+
| DecisionTree | 0.7951627351448194 | 0.7946651495797598 | 0.7944744407574804 | 0.7945626591695996 |
|     kNN      | 0.7363392057330547 | 0.735841010813109  | 0.7348398435265175 | 0.7351543688776938 |
|    Forest    | 0.848014332636608  | 0.8487123085321602 | 0.849466681446307  | 0.8479804475060466 |
| Naive Bayes  | 0.7438041206330248 | 0.7509054749561079 | 0.7386402969277419 | 0.7387679306911467 |
+--------------+--------------------+--------------------+--------------------+--------------------+

#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3.

In [11]:
#code


importances = clf.feature_importances_
#sort
sorted_idx = np.argsort(importances)[::-1]
#print rank
for idx in sorted_idx:
    print(f"{importances[idx]}")


    #lay tu 0.01
sfm = SelectFromModel(clf, threshold=0.01)
X_train = sfm.fit_transform(X_train, y_train)
X_test = sfm.transform(X_test)




decision = tree.DecisionTreeClassifier()
decision.fit(X_train, y_train) 
y_predDes = decision.predict(X_test)


clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_predForest = clf.predict(X_test)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_predKnn = neigh.predict(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_predNaiveBayes = model.predict(X_test)


t = PrettyTable(["Regression","accuracy","precision","recall","f1"])

t.add_row(["DecisionTree",accuracy_score(y_test,y_predDes),
           precision_score(y_test,y_predDes,average='macro'),
           recall_score(y_test,y_predDes,average='macro'),
           f1_score(y_test,y_predDes,average='macro')])


t.add_row(["kNN",accuracy_score(y_test,y_predKnn),
           precision_score(y_test,y_predKnn,average='macro'),
           recall_score(y_test,y_predKnn,average='macro'),
           f1_score(y_test,y_predKnn,average='macro')])

t.add_row(["Forest",accuracy_score(y_test,y_predForest),
           precision_score(y_test,y_predForest,average='macro'),
           recall_score(y_test,y_predForest,average='macro'),
           f1_score(y_test,y_predForest,average='macro')])
t.add_row(["Naive Bayes",accuracy_score(y_test,y_predNaiveBayes),
           precision_score(y_test,y_predNaiveBayes,average='macro'),
           recall_score(y_test,y_predNaiveBayes,average='macro'),
           f1_score(y_test,y_predNaiveBayes,average='macro')])


print(t)

0.32902075345110654
0.07611700026470222
0.07509795449537914
0.06427516813537033
0.0339312543342511
0.032304091856041176
0.032173765029933875
0.02367322662349187
0.02290598896125827
0.018201839468578746
0.015681307688174214
0.014801338683416508
0.013995415845286147
0.012928729651171398
0.012589943007614188
0.010764776808736247
0.01068414773364134
0.01065165893468579
0.009959085065302676
0.009567081278741505
0.009518045245619933
0.009299513753082701
0.009093359806706607
0.008936718021453986
0.008763117422334581
0.00861157479279696
0.00836955505591038
0.00836160156140617
0.007996783307251136
0.00744938039264931
0.007117847540597237
0.006826535702268256
0.006510525794459316
0.005720106549889768
0.005424785502135937
0.005421858631584293
0.004738671923621012
0.004723139238913127
0.0046791917657157765
0.004619835833756205
0.0038431411568294617
0.00370058740484491
0.0036827565799277765
0.003484938690935211
0.0034470999160199135
0.0031240395534454803
0.002430196493272777
0.0015195156505118826
0.0011653435636117186
0.0011355819974043083
0.0009601238341606871
+--------------+--------------------+--------------------+--------------------+--------------------+
|  Regression  |      accuracy      |     precision      |       recall       |         f1         |
+--------------+--------------------+--------------------+--------------------+--------------------+
| DecisionTree | 0.777246939384891  | 0.7767369540464477 | 0.7763589521711769 | 0.776520038785901  |
|     kNN      | 0.7363392057330547 | 0.735841010813109  | 0.7348398435265175 | 0.7351543688776938 |
|    Forest    | 0.8438339802926247 | 0.8444361278335244 | 0.8452142571085303 | 0.8437933680761018 |
| Naive Bayes  | 0.751269035532995  | 0.7693590285152565 | 0.743969370387322  | 0.7428492155414104 |
+--------------+--------------------+--------------------+--------------------+--------------------+

#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.

In [12]:
# code

dataSet = pd.read_csv("creditcard.csv")

X = dataSet.drop('Class', axis=1)
y = dataSet['Class']
#Chuan hoa du lieu
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)



X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size=0.3, random_state=1)

decision = tree.DecisionTreeClassifier()
decision.fit(X_train, y_train) 
y_predDes = decision.predict(X_test)


clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_predForest = clf.predict(X_test)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_predKnn = neigh.predict(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_predNaiveBayes = model.predict(X_test)


t = PrettyTable(["Regression","accuracy","precision","recall","f1"])

t.add_row(["DecisionTree",accuracy_score(y_test,y_predDes),
           precision_score(y_test,y_predDes,average='macro'),
           recall_score(y_test,y_predDes,average='macro'),
           f1_score(y_test,y_predDes,average='macro')])


t.add_row(["kNN",accuracy_score(y_test,y_predKnn),
           precision_score(y_test,y_predKnn,average='macro'),
           recall_score(y_test,y_predKnn,average='macro'),
           f1_score(y_test,y_predKnn,average='macro')])

t.add_row(["Forest",accuracy_score(y_test,y_predForest),
           precision_score(y_test,y_predForest,average='macro'),
           recall_score(y_test,y_predForest,average='macro'),
           f1_score(y_test,y_predForest,average='macro')])
t.add_row(["Naive Bayes",accuracy_score(y_test,y_predNaiveBayes),
           precision_score(y_test,y_predNaiveBayes,average='macro'),
           recall_score(y_test,y_predNaiveBayes,average='macro'),
           f1_score(y_test,y_predNaiveBayes,average='macro')])


print(t)

+--------------+--------------------+--------------------+--------------------+--------------------+
|  Regression  |      accuracy      |     precision      |       recall       |         f1         |
+--------------+--------------------+--------------------+--------------------+--------------------+
| DecisionTree | 0.9991807403766253 | 0.8719694559338211 | 0.8664673887560369 | 0.8691978484536371 |
|     kNN      | 0.9995318516437859 | 0.9717634042978214 | 0.874038907383963  | 0.9172381688347941 |
|    Forest    | 0.9994967405170698 | 0.9515668764429444 | 0.8814170092162777 | 0.9135286200093187 |
| Naive Bayes  | 0.9787343609189753 | 0.5280497292284355 | 0.8858107615281621 | 0.5473030512618944 |
+--------------+--------------------+--------------------+--------------------+--------------------+

In [ ]:
importances2 = clf.feature_importances_
#sort
sorted_idx = np.argsort(importances)[::-1]
#print rank
for idx in sorted_idx:
    print(f"{importances[idx]}")  

sfm = SelectFromModel(clf, threshold=0.012)
X_train = sfm.fit_transform(X_train, y_train)
X_test = sfm.transform(X_test)


decision = tree.DecisionTreeClassifier()
decision.fit(X_train, y_train) 
y_predDes = decision.predict(X_test)


clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_predForest = clf.predict(X_test)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_predKnn = neigh.predict(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_predNaiveBayes = model.predict(X_test)


t = PrettyTable(["Regression","accuracy","precision","recall","f1"])

t.add_row(["DecisionTree",accuracy_score(y_test,y_predDes),
           precision_score(y_test,y_predDes,average='macro'),
           recall_score(y_test,y_predDes,average='macro'),
           f1_score(y_test,y_predDes,average='macro')])


t.add_row(["kNN",accuracy_score(y_test,y_predKnn),
           precision_score(y_test,y_predKnn,average='macro'),
           recall_score(y_test,y_predKnn,average='macro'),
           f1_score(y_test,y_predKnn,average='macro')])

t.add_row(["Forest",accuracy_score(y_test,y_predForest),
           precision_score(y_test,y_predForest,average='macro'),
           recall_score(y_test,y_predForest,average='macro'),
           f1_score(y_test,y_predForest,average='macro')])
t.add_row(["Naive Bayes",accuracy_score(y_test,y_predNaiveBayes),
           precision_score(y_test,y_predNaiveBayes,average='macro'),
           recall_score(y_test,y_predNaiveBayes,average='macro'),
           f1_score(y_test,y_predNaiveBayes,average='macro')])


print(t)

0.32902075345110654
0.07611700026470222
0.07509795449537914
0.06427516813537033
0.0339312543342511
0.032304091856041176
0.032173765029933875
0.02367322662349187
0.02290598896125827
0.018201839468578746
0.015681307688174214
0.014801338683416508
0.013995415845286147
0.012928729651171398
0.012589943007614188
0.010764776808736247
0.01068414773364134
0.01065165893468579
0.009959085065302676
0.009567081278741505
0.009518045245619933
0.009299513753082701
0.009093359806706607
0.008936718021453986
0.008763117422334581
0.00861157479279696
0.00836955505591038
0.00836160156140617
0.007996783307251136
0.00744938039264931
0.007117847540597237
0.006826535702268256
0.006510525794459316
0.005720106549889768
0.005424785502135937
0.005421858631584293
0.004738671923621012
0.004723139238913127
0.0046791917657157765
0.004619835833756205
0.0038431411568294617
0.00370058740484491
0.0036827565799277765
0.003484938690935211
0.0034470999160199135
0.0031240395534454803
0.002430196493272777
0.0015195156505118826
0.0011653435636117186
0.0011355819974043083
0.0009601238341606871

#Finally,
Save a copy in your Github. Remember renaming the notebook.